.386
STACK	SEGMENT USE16 STACK
        DB 200 DUP(0)
STACK 	ENDS
DATA	SEGMENT USE16
TIME	DB '00:00:00$'
DATA	ENDS

CODE	SEGMENT USE16
		ASSUME  CS:CODE, SS:STACK, DS:DATA, ES:DATA
PRINT_TIME PROC
		PUSH EAX
		PUSH EDX
		; hours
		MOV AL, 4H
		OUT 70H, AL
		IN AL, 71H
		MOV AH, AL
		SHR AH, 4
		AND AL, 0FH
		ADD AH, '0'
		ADD AL, '0'
		MOV TIME[0], AH
		MOV TIME[1], AL
		; miuntes
		MOV AL, 2
		OUT 70H, AL
		IN AL, 71H
		MOV AH, AL
		SHR AH, 4
		AND AL, 0FH
		ADD AH, '0'
		ADD AL, '0'
		MOV TIME[3], AH
		MOV TIME[4], AL
		; seconds
		MOV AL, 0
		OUT 70H, AL
		IN AL, 71H
		MOV AH, AL
		SHR AH, 4
		AND AL, 0FH
		ADD AH, '0'
		ADD AL, '0'
		MOV TIME[6], AH
		MOV TIME[7], AL
		MOV DX, OFFSET TIME
		MOV AH, 9
		INT 21H
		POP EDX
		POP EAX
		RET
PRINT_TIME ENDP
START:
		MOV AX, DATA
		MOV DS, AX
		; code after this
		CALL PRINT_TIME
		;stop here
		MOV  AH, 4CH
		INT  21H
CODE 	ENDS
		END  START
