.386
STACK	SEGMENT USE16 STACK
        DB 200 DUP(0)
STACK 	ENDS
DATA	SEGMENT USE16
DATA	ENDS

CODE	SEGMENT USE16
		ASSUME  CS:CODE, SS:STACK, DS:DATA, ES:DATA
START:
		MOV AX, DATA
		MOV DS, AX
		; code after this

		;stop here
		MOV  AH, 4CH
		INT  21H	
CODE 	ENDS
		END  START
