.386
STACK	SEGMENT USE16 STACK
        DB 200 DUP(0)
STACK 	ENDS

DATA	SEGMENT USE16
BUF1 	DB 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
BUF2 	DB 10 DUP(0)
BUF3	DB 10 DUP(0)
BUF4	DB 10 DUP(0)
DATA	ENDS

CODE	SEGMENT USE16
		ASSUME  CS:CODE, DS:DATA, SS:DATA
START:
		MOV AX, DATA
		MOV DS, AX
		; code after here
		MOV ESI, OFFSET BUF1
		MOV CX, 10
LOPA:	MOV AL, [ESI]
		MOV [ESI + 10], AL; according memory order
		INC AL
		MOV [ESI + 20], AL
		ADD AL, 3
		MOV DS:[ESI + 30], AL
		INC ESI
		DEC CX
		JNZ LOPA
		;stop here
		MOV AH, 4CH
		INT 21H	
CODE 	ENDS
		END START
